// src/components/Sqc_index.vue
<template>
  <div class="animation-container">
    <canvas ref="canvas" width="1080" height="1080"></canvas>
  </div>
</template>

<script>
export default {
  name: 'SqcIndex',
  data() {
    return {
      canvas: null,
      ctx: null,
      currentFrame: 0,
      totalFrames: 0,
      frameCache: new Map(), // 用于缓存已加载的图片
      isLoading: false,
      animationId: null,
      fps: 30, // 帧率
      preloadCount: 5, // 预加载的帧数
    }
  },
  mounted() {
    this.initCanvas()
    this.startAnimation()
  },
  beforeUnmount() {
    this.stopAnimation()
  },
  methods: {
    initCanvas() {
      this.canvas = this.$refs.canvas
      this.ctx = this.canvas.getContext('2d')
    },
    
    async startAnimation() {
      // 获取总帧数（这里假设帧数从1开始，到某个最大值）
      this.totalFrames = 150 // 根据实际帧数调整
      this.currentFrame = 1
      
      // 开始动画循环
      this.animate()
      
      // 预加载初始帧
      await this.preloadFrames(1)
    },
    
    async animate() {
      if (this.currentFrame > this.totalFrames) {
        this.currentFrame = 1 // 循环播放
      }
      
      // 绘制当前帧
      await this.drawFrame(this.currentFrame)
      
      // 预加载后续帧
      this.preloadFrames(this.currentFrame + 1)
      
      // 更新帧计数
      this.currentFrame++
      
      // 继续下一帧
      this.animationId = requestAnimationFrame(() => {
        setTimeout(() => this.animate(), 1000 / this.fps)
      })
    },
    
    async drawFrame(frameNumber) {
      // 如果帧已经在缓存中，直接使用
      if (this.frameCache.has(frameNumber)) {
        const img = this.frameCache.get(frameNumber)
        this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height)
        this.ctx.drawImage(img, 0, 0)
        return
      }
      
      // 如果帧不在缓存中，加载它
      try {
        const img = await this.loadFrame(frameNumber)
        this.frameCache.set(frameNumber, img)
        this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height)
        this.ctx.drawImage(img, 0, 0)
      } catch (error) {
        console.error(`Error loading frame ${frameNumber}:`, error)
      }
    },
    
    async preloadFrames(startFrame) {
      if (this.isLoading) return
      this.isLoading = true
      
      try {
        const promises = []
        for (let i = 0; i < this.preloadCount; i++) {
          const frameNumber = startFrame + i
          if (frameNumber <= this.totalFrames && !this.frameCache.has(frameNumber)) {
            promises.push(this.loadFrame(frameNumber))
          }
        }
        
        const images = await Promise.all(promises)
        images.forEach((img, index) => {
          const frameNumber = startFrame + index
          this.frameCache.set(frameNumber, img)
        })
      } catch (error) {
        console.error('Error preloading frames:', error)
      } finally {
        this.isLoading = false
      }
    },
    
    loadFrame(frameNumber) {
      return new Promise((resolve, reject) => {
        const img = new Image()
        img.onload = () => resolve(img)
        img.onerror = reject
        // 使用 webp 格式的图片
        img.src = `/frame_webp/frame_${String(frameNumber).padStart(4, '0')}.webp`
      })
    },
    
    stopAnimation() {
      if (this.animationId) {
        cancelAnimationFrame(this.animationId)
        this.animationId = null
      }
      this.frameCache.clear()
    }
  }
}
</script>

<style scoped>
.animation-container {
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
}

canvas {
  max-width: 100%;
  height: auto;
}
</style>

// Vite_Front-end/component/sqc_index.tsx
import React, { useRef, useEffect, useState } from 'react';

const TOTAL_FRAMES = 150;
const FPS = 30;
const PRELOAD_COUNT = 5;
const BASE_WIDTH = 1080;
const BASE_HEIGHT = 1080;

const SqcIndex: React.FC = () => {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const frameCache = useRef<Map<number, HTMLImageElement>>(new Map());
  const currentFrame = useRef(1);
  const animationId = useRef<number | null>(null);
  const isLoading = useRef(false);

  // xiong.webp 相关
  const xiongImgRef = useRef<HTMLImageElement | null>(null);
  const xiongLoaded = useRef(false);
  const xiongRectRef = useRef<{x: number, y: number, w: number, h: number} | null>(null);

  const [paused, setPaused] = useState(false);

  // 动态调整 Canvas 分辨率和样式尺寸
  const resizeCanvas = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const container = canvas.parentElement;
    if (!container) return;
    const containerWidth = container.clientWidth;
    const containerHeight = container.clientHeight;
    let scale = Math.min(containerWidth / BASE_WIDTH, containerHeight / BASE_HEIGHT);
    if (!isFinite(scale) || scale <= 0) scale = 1;
    canvas.width = Math.round(BASE_WIDTH * scale);
    canvas.height = Math.round(BASE_HEIGHT * scale);
    canvas.style.width = `${Math.round(BASE_WIDTH * scale)}px`;
    canvas.style.height = `${Math.round(BASE_HEIGHT * scale)}px`;
  };

  // 加载单帧图片
  const loadFrame = (frameNumber: number): Promise<HTMLImageElement> => {
    return new Promise((resolve, reject) => {
      const img = new window.Image();
      img.onload = () => resolve(img);
      img.onerror = reject;
      img.src = `/frame_webp/frame_${String(frameNumber).padStart(4, '0')}.webp`;
    });
  };

  // 预加载后续帧
  const preloadFrames = async (startFrame: number) => {
    if (isLoading.current) return;
    isLoading.current = true;
    try {
      const promises: Promise<HTMLImageElement>[] = [];
      for (let i = 0; i < PRELOAD_COUNT; i++) {
        const frameNumber = startFrame + i;
        if (frameNumber <= TOTAL_FRAMES && !frameCache.current.has(frameNumber)) {
          promises.push(loadFrame(frameNumber));
        }
      }
      const images = await Promise.all(promises);
      images.forEach((img, index) => {
        const frameNumber = startFrame + index;
        frameCache.current.set(frameNumber, img);
      });
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error('Error preloading frames:', error);
    } finally {
      isLoading.current = false;
    }
  };

  // 绘制当前帧（如果未加载则跳过该帧）
  const drawFrame = (frameNumber: number) => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    const img = frameCache.current.get(frameNumber);
    if (!img) {
      // 跳过未加载的帧
      return false;
    }
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

    // 绘制 xiong.webp
    if (xiongLoaded.current && xiongImgRef.current) {
      const progress = (frameNumber - 1) / (TOTAL_FRAMES - 1);
      const startX = -canvas.width * 0.3;
      const endX = canvas.width * 1.1;
      const x = startX + (endX - startX) * progress;
      const y = canvas.height / 2;
      const rotateY = Math.PI * progress;
      const scale = 0.5 + 0.5 * Math.abs(Math.cos(rotateY));
      const imgW = (canvas.width / 4) * scale;
      const imgH = (canvas.height / 4) * scale;
      xiongRectRef.current = { x: x - imgW / 2, y: y - imgH / 2, w: imgW, h: imgH };
      ctx.save();
      ctx.translate(x, y);
      ctx.transform(Math.cos(rotateY), 0, 0, 1, 0, 0);
      ctx.drawImage(
        xiongImgRef.current,
        -imgW / 2,
        -imgH / 2,
        imgW,
        imgH
      );
      ctx.restore();
    } else {
      xiongRectRef.current = null;
    }
  };

  // 动画主循环（彻底唯一化）
  function animate() {
    if (paused) {
      animationId.current = null;
      return;
    }
    if (currentFrame.current > TOTAL_FRAMES) {
      currentFrame.current = 1;
    }
    drawFrame(currentFrame.current);
    preloadFrames(currentFrame.current + 1);
    currentFrame.current++;
    animationId.current = window.requestAnimationFrame(animate);
  }

  // 只在挂载时启动一次动画主循环
  useEffect(() => {
    currentFrame.current = 1;
    frameCache.current.clear();
    resizeCanvas();
    if (animationId.current) {
      window.cancelAnimationFrame(animationId.current);
      animationId.current = null;
    }
    animationId.current = window.requestAnimationFrame(animate);
    preloadFrames(1);

    // 加载 xiong.webp
    const xiongImg = new window.Image();
    xiongImg.onload = () => {
      xiongImgRef.current = xiongImg;
      xiongLoaded.current = true;
    };
    xiongImg.src = '/xiong.webp';

    // 绑定点击事件
    const handleClick = (e: MouseEvent) => {
      const canvas = canvasRef.current;
      if (!canvas || !xiongRectRef.current) return;
      const rect = canvas.getBoundingClientRect();
      const clickX = e.clientX - rect.left;
      const clickY = e.clientY - rect.top;
      const { x, y, w, h } = xiongRectRef.current;
      if (
        clickX >= x && clickX <= x + w &&
        clickY >= y && clickY <= y + h
      ) {
        setPaused(p => !p);
      }
    };
    if (canvasRef.current) {
      canvasRef.current.addEventListener('click', handleClick);
    }
    window.addEventListener('resize', resizeCanvas);

    return () => {
      if (animationId.current) {
        window.cancelAnimationFrame(animationId.current);
        animationId.current = null;
      }
      frameCache.current.clear();
      if (canvasRef.current) {
        canvasRef.current.removeEventListener('click', handleClick);
      }
      window.removeEventListener('resize', resizeCanvas);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // paused 状态变化时，彻底 cancel/恢复动画主循环
  useEffect(() => {
    if (paused) {
      if (animationId.current) {
        window.cancelAnimationFrame(animationId.current);
        animationId.current = null;
      }
    } else {
      if (!animationId.current) {
        animationId.current = window.requestAnimationFrame(animate);
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [paused]);

  return (
    <div className="animation-container" style={{ width: '100%', height: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
      <canvas ref={canvasRef} style={{ maxWidth: '100%', height: 'auto' }} />
    </div>
  );
};

export default SqcIndex;
